const ingredients = [
  { value: "olive_oil", label: "Olive oil" },
  { value: "garlic", label: "Garlic" },
  { value: "greek-yogurt", label: "Greek Yogurt" },
  { value: "onion", label: "Onion" },
  { value: "salt", label: "Salt" },
  { value: "black_pepper", label: "Black pepper" },
  { value: "chicken_breast", label: "Chicken breast" },
  { value: "beef", label: "Beef" },
  { value: "pork", label: "Pork" },
  { value: "shrimp", label: "Shrimp" },
  { value: "salmon", label: "Salmon" },
  { value: "tomato", label: "Tomato" },
  { value: "carrot", label: "Carrot" },
  { value: "potato", label: "Potato" },
  { value: "bell_pepper", label: "Bell pepper" },
  { value: "broccoli", label: "Broccoli" },
  { value: "spinach", label: "Spinach" },
  { value: "kale", label: "Kale" },
  { value: "cabbage", label: "Cabbage" },
  { value: "mushroom", label: "Mushroom" },
  { value: "zucchini", label: "Zucchini" },
  { value: "eggplant", label: "Eggplant" },
  { value: "cucumber", label: "Cucumber" },
  { value: "lettuce", label: "Lettuce" },
  { value: "celery", label: "Celery" },
  { value: "green_beans", label: "Green beans" },
  { value: "asparagus", label: "Asparagus" },
  { value: "peas", label: "Peas" },
  { value: "corn", label: "Corn" },
  { value: "rice", label: "Rice" },
  { value: "pasta", label: "Pasta" },
  { value: "flour", label: "Flour" },
  { value: "sugar", label: "Sugar" },
  { value: "brown_sugar", label: "Brown sugar" },
  { value: "honey", label: "Honey" },
  { value: "soy_sauce", label: "Soy sauce" },
  { value: "vinegar", label: "Vinegar" },
  { value: "lemon", label: "Lemon" },
  { value: "lime", label: "Lime" },
  { value: "orange", label: "Orange" },
  { value: "apple", label: "Apple" },
  { value: "banana", label: "Banana" },
  { value: "grape", label: "Grape" },
  { value: "strawberry", label: "Strawberry" },
  { value: "blueberry", label: "Blueberry" },
  { value: "raspberry", label: "Raspberry" },
  { value: "mango", label: "Mango" },
  { value: "pineapple", label: "Pineapple" },
  { value: "watermelon", label: "Watermelon" },
  { value: "avocado", label: "Avocado" },
  { value: "cheese", label: "Cheese" },
  { value: "milk", label: "Milk" },
  { value: "butter", label: "Butter" },
  { value: "yogurt", label: "Yogurt" },
  { value: "eggs", label: "Eggs" },
  { value: "bread", label: "Bread" },
  { value: "bacon", label: "Bacon" },
  { value: "sausage", label: "Sausage" },
  { value: "ham", label: "Ham" },
  { value: "tofu", label: "Tofu" },
  { value: "lentils", label: "Lentils" },
  { value: "chickpeas", label: "Chickpeas" },
  { value: "black_beans", label: "Black beans" },
  { value: "kidney_beans", label: "Kidney beans" },
  { value: "quinoa", label: "Quinoa" },
  { value: "oats", label: "Oats" },
  { value: "almonds", label: "Almonds" },
  { value: "walnuts", label: "Walnuts" },
  { value: "peanuts", label: "Peanuts" },
  { value: "peanut_butter", label: "Peanut butter" },
  { value: "mustard", label: "Mustard" },
  { value: "ketchup", label: "Ketchup" },
  { value: "mayonnaise", label: "Mayonnaise" },
  { value: "hot_sauce", label: "Hot sauce" },
  { value: "basil", label: "Basil" },
  { value: "oregano", label: "Oregano" },
  { value: "thyme", label: "Thyme" },
  { value: "rosemary", label: "Rosemary" },
  { value: "parsley", label: "Parsley" },
  { value: "dill", label: "Dill" },
  { value: "cilantro", label: "Cilantro" },
  { value: "cumin", label: "Cumin" },
  { value: "paprika", label: "Paprika" },
  { value: "turmeric", label: "Turmeric" },
  { value: "ginger", label: "Ginger" },
  { value: "cinnamon", label: "Cinnamon" },
  { value: "nutmeg", label: "Nutmeg" },
  { value: "cloves", label: "Cloves" },
  { value: "bay_leaves", label: "Bay leaves" },
  { value: "chili_powder", label: "Chili powder" },
  { value: "curry_powder", label: "Curry powder" },
  { value: "saffron", label: "Saffron" },
  { value: "vanilla_extract", label: "Vanilla extract" },
  { value: "baking_powder", label: "Baking powder" },
  { value: "baking_soda", label: "Baking soda" },
  { value: "yeast", label: "Yeast" },
  { value: "cocoa_powder", label: "Cocoa powder" },
  { value: "coconut_milk", label: "Coconut milk" },
  { value: "tomato_paste", label: "Tomato paste" },
  { value: "chicken_broth", label: "Chicken broth" },
  { value: "beef_broth", label: "Beef broth" }
];

export default ingredients